const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("desktopAPI", {
  getPinned: () => ipcRenderer.invoke("window:get-pinned"),
  togglePinned: () => ipcRenderer.invoke("window:toggle-pinned"),
  getLocked: () => ipcRenderer.invoke("window:get-locked"),
  toggleLocked: () => ipcRenderer.invoke("window:toggle-locked"),
  onLockChanged: callback => ipcRenderer.on("window:lock-changed", (_event, locked) => callback(locked)),
  getGlass: () => ipcRenderer.invoke("window:get-glass"),
  toggleGlass: () => ipcRenderer.invoke("window:toggle-glass"),
  onGlassChanged: callback => ipcRenderer.on("window:glass-changed", (_event, glass) => callback(glass)),
  onUpdateProgress: callback => ipcRenderer.on("app:update-progress", (_event, payload) => callback(payload)),
  getSettings: () => ipcRenderer.invoke("app:get-settings"),
  saveSettings: settings => ipcRenderer.invoke("app:save-settings", settings),
  aiAsk: payload => ipcRenderer.invoke("ai:ask", payload),
  aiDetectProvider: payload => ipcRenderer.invoke("ai:detect-provider", payload),
  aiListModels: payload => ipcRenderer.invoke("ai:list-models", payload),
  getVersion: () => ipcRenderer.invoke("app:get-version"),
  checkForUpdates: () => ipcRenderer.invoke("app:check-for-updates"),
  getPaths: () => ipcRenderer.invoke("app:get-paths"),
  resizeBy: (width, height) => ipcRenderer.send("window:resize-by", width, height),
  setWindowBounds: bounds => ipcRenderer.send("window:set-bounds", bounds),
  minimize: () => ipcRenderer.invoke("window:minimize"),
  isMaximized: () => ipcRenderer.invoke("window:is-maximized"),
  toggleMaximize: () => ipcRenderer.invoke("window:toggle-maximize"),
  onMaximizeChanged: callback => ipcRenderer.on("window:maximize-changed", (_event, maximized) => callback(maximized)),
  quit: () => ipcRenderer.invoke("app:quit"),
  loadPlannerData: () => ipcRenderer.invoke("data:load-store"),
  savePlannerData: data => ipcRenderer.invoke("data:save-store", data),
  exportData: (filename, format, data) => ipcRenderer.invoke("data:export", filename, format, data)
});
