const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const app = fs.readFileSync(path.join(__dirname, "..", "app.js"), "utf8");
const html = fs.readFileSync(path.join(__dirname, "..", "index.html"), "utf8");
const preload = fs.readFileSync(path.join(__dirname, "..", "preload.js"), "utf8");
const styles = fs.readFileSync(path.join(__dirname, "..", "styles.css"), "utf8");

assert.match(html, /id="taskAiDropzone"/, "new-task dialog needs screenshot dropzone");
assert.match(html, /id="aiBatchDraftDialog"/, "multi-todo review dialog must exist");
assert.match(html, /id="aiPrompt"/, "AI dialog needs single message box");
assert.doesNotMatch(html, /id="aiChatLog"/, "AI dialog should not keep a separate chat log pane");
assert.match(html, /id="aiAttachment"/, "AI dialog needs attachment preview");
assert.match(app, /Shift\+Enter|shiftKey/, "AI message box must support keyboard send shortcuts");
assert.match(html, /ai-task-draft-policy\.js/, "renderer must load draft policy");
assert.match(preload, /aiExtractTask/, "preload must expose aiExtractTask");
assert.match(app, /createTaskFromAiDraft/, "renderer must create tasks from AI drafts");
assert.match(app, /createTasksFromAiDrafts/, "batch create helper must exist");
assert.match(app, /openAiBatchDraftDialog/, "multi drafts open review dialog");
assert.match(app, /extractAndCreateTaskFromImage/, "screenshot create pipeline must exist");
assert.match(html, /id="aiDialogScroll"/, "AI dialog scroll region must remain available");
assert.match(app, /showAiMessageInBox/, "AI replies should reuse the single message box");
assert.match(app, /setupIncomplete:\s*true/, "screenshot tasks should start as setup-incomplete");
assert.match(app, /promoteSetupIncompleteSections/, "incomplete screenshot tasks should pin to the top");
assert.match(app, /task-setup-warning/, "incomplete tasks should show a warning mark instead of a checkbox");
assert.match(styles, /\.task-setup-warning-mark/, "warning mark needs yellow triangle styles");
assert.match(app, /createMeetingFromAiDraft/, "screenshot pipeline must create meetings when kind=meeting");
assert.match(app, /createItemsFromAiDrafts/, "batch create must route task vs meeting drafts");
assert.match(app, /data-field="kind"/, "batch review must let users correct task/meeting kind");
assert.doesNotMatch(html, /id="aiBatchSharedParent"/, "batch dialog should not force parent dropdown before create");
assert.doesNotMatch(app, /aiBatchApplyParentButton/, "batch create should not apply shared parents in the review dialog");
assert.match(html, /id="taskCreateKind"/, "create dialog must expose task/meeting kind in one form");
assert.match(html, /id="taskMeetingEndDateTime"/, "meeting create must expose end datetime");
assert.match(app, /openNewFromQuickAdd/, "quick-add opens a single create dialog");
assert.match(app, /syncTaskCreateKindUi|saveMeetingFromCreateDialog/, "create form must switch and save meeting kind");
assert.match(app, /请填写结束日期时间/, "meeting save must require end datetime");
assert.doesNotMatch(html, /data-create-kind="screenshot"/, "must not keep a separate screenshot menu entry");
assert.doesNotMatch(html, /id="createKindMenu"/, "must not force task/meeting/screenshot chooser before create");
assert.match(app, /handlePanelScreenshotPaste/, "panel must accept paste screenshot for AI extract");
assert.match(app, /exportAiTables/, "AI assistant must support table file export");
assert.match(app, /copyTextToClipboard/, "AI copy must use a reliable clipboard helper");
assert.match(app, /writeClipboardText/, "AI copy should prefer desktop clipboard bridge");
assert.match(html, /id="aiExportTablesButton"/, "AI dialog needs Excel download button");
assert.match(html, /id="taskCloseCompletedAt"/, "close confirm needs completion time");
assert.match(html, /id="taskCloseCompletionNote"/, "close confirm needs completion note");
assert.match(html, /id="taskCloseSuccessorButton"/, "close confirm needs successor action");

console.log("ai screenshot ui tests passed");
